//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class autori_knjiga
    {
        public int id_knjiga_autor { get; set; }
        public int knjigaid_knjiga { get; set; }
        public int autorid_autor { get; set; }
        public System.DateTime datum_upisa { get; set; }
    
        public virtual autor autor { get; set; }
        public virtual knjiga knjiga { get; set; }
    }
}
