//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class knjiga
    {
        public knjiga()
        {
            this.autori_knjiga = new HashSet<autori_knjiga>();
            this.knjiga_vrsta = new HashSet<knjiga_vrsta>();
            this.komentari = new HashSet<komentari>();
            this.posudba = new HashSet<posudba>();
        }
    
        public int id_knjiga { get; set; }
        public string isbn { get; set; }
        public string naslov { get; set; }
        public string godina_izdanja { get; set; }
        public string tema { get; set; }
        public Nullable<int> izdanje { get; set; }
        public int kolicina { get; set; }
        public int izdavacid_izdavac { get; set; }
        public int korisniciid_korisnici { get; set; }
    
        public virtual ICollection<autori_knjiga> autori_knjiga { get; set; }
        public virtual izdavac izdavac { get; set; }
        public virtual ICollection<knjiga_vrsta> knjiga_vrsta { get; set; }
        public virtual korisnici korisnici { get; set; }
        public virtual ICollection<komentari> komentari { get; set; }
        public virtual ICollection<posudba> posudba { get; set; }
    }
}
