//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class posudba
    {
        public int id_posudba { get; set; }
        public int knjigaid_knjiga { get; set; }
        public int korisniciid_korisnici { get; set; }
        public int korisniciid_korisnici2 { get; set; }
        public System.DateTime datum_posudbe { get; set; }
        public System.DateTime datum_vracanja { get; set; }
    
        public virtual knjiga knjiga { get; set; }
        public virtual korisnici korisnici { get; set; }
        public virtual korisnici korisnici1 { get; set; }
    }
}
