//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrsta
    {
        public vrsta()
        {
            this.knjiga_vrsta = new HashSet<knjiga_vrsta>();
        }
    
        public int id_vrsta { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<knjiga_vrsta> knjiga_vrsta { get; set; }
    }
}
