//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class knjiga_vrsta
    {
        public int id_knjiga_vrsta { get; set; }
        public int knjigaid_knjiga { get; set; }
        public int vrstaid_vrsta { get; set; }
    
        public virtual knjiga knjiga { get; set; }
        public virtual vrsta vrsta { get; set; }
    }
}
