//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prava
    {
        public prava()
        {
            this.korisnici = new HashSet<korisnici>();
        }
    
        public int id_prava { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<korisnici> korisnici { get; set; }
    }
}
