//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booker.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookerDBEntities : DbContext
    {
        public BookerDBEntities()
            : base("name=BookerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<autori_knjiga> autori_knjiga { get; set; }
        public virtual DbSet<izdavac> izdavac { get; set; }
        public virtual DbSet<knjiga> knjiga { get; set; }
        public virtual DbSet<knjiga_vrsta> knjiga_vrsta { get; set; }
        public virtual DbSet<komentari> komentari { get; set; }
        public virtual DbSet<korisnici> korisnici { get; set; }
        public virtual DbSet<posudba> posudba { get; set; }
        public virtual DbSet<prava> prava { get; set; }
        public virtual DbSet<vrsta> vrsta { get; set; }
    }
}
